### ISSUE TITLE
Documentation is not updated.

### ISSUE THREAD

**Issue by DavidShochet** [BulletTrainHQ/bullet-train-examples#1]
I am trying to use Bullet Train of the latest version (2.0.0) on my mobile app. In your documentation, I find:

```
BulletTrainClient bulletClient = new BulletTrainClient() {
  environmentKey: "<environment-key-here>"
};
```

 
But when I use it, the constructor requires a parameter. It works when I downgrade to the previous version of Bullet Train. 
Could you please tell how the new version should be used?

**Comment by bullettrainio** [comment]
Sorry - which language SDK is this?

**Comment by DavidShochet** [comment]
.Net, C#

**Comment by dabeeeenster** [comment]
The documentation for .net shows you need to pass in a configuration object: 

```
BulletTrainConfiguration configuration = new BulletTrainConfiguration()
{
    ApiUrl = "https://api.bullet-train.io/api/v1/",
    EnvironmentKey = "env-key-goes-here"
};

BulletTrainClient bulletClient = new BulletTrainClient(configuration);
```

What documentation are you referring to?

**Comment by DavidShochet** [comment]
It is here:

https://docs.bullet-train.io/clients/dotnet/

**Comment by dabeeeenster** [comment]
Ah thanks - Ive updated the docs this should make sense now

**Comment by DavidShochet** [comment]
Thank you!
